### ISSUE TITLE
unittest doesnt compile

### ISSUE THREAD

**Issue by logicfish** [mbierlee/poodinis#19] opened 2017-07-29 09:00 UTC
class ExampleClassA {}

class ExampleClassB {
	@Autowire
	private ExampleClassA dependency;
}

auto dependencies = new shared DependencyContainer();
dependencies.register!ExampleClassA;
auto exampleInstance = new ExampleClassB();
dependencies.autowire(exampleInstance);
assert(exampleInstance.dependency !is null);

..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\autowire.d-mixin-271(271,37): Error: no property 'ExampleClassA' for type 'void'
..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\autowire.d-mixin-271(271,37): Error: no property 'ExampleClassA' for type 'void'
..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\autowire.d-mixin-271(271,37): Error: no property 'ExampleClassA' for type 'void'
..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\autowire.d-mixin-271(271,37): Error: no property 'ExampleClassA' for type 'void'
..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\autowire.d-mixin-271(271,37): Error: no property 'ExampleClassA' for type 'void'
..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\autowire.d-mixin-271(271,37): Error: no property 'ExampleClassA' for type 'void'
..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\container.d(180,30): Error: template instance poodinis.autowire.AutowiredRegistration!(ExampleClassA) error instantiating
..\..\..\AppData\Roaming\dub\packages\poodinis-8.0.0\poodinis\source\poodinis\container.d(146,47):        instantiated from here: register!(ExampleClassA, ExampleClassA)
......:        instantiated from here: register!(ExampleClassA)

**Comment by logicfish** [comment] 2017-07-29 09:00
DMD32 D Compiler v2.075.0
Copyright (c) 1999-2017 by Digital Mars written by Walter Bright

**Comment by mbierlee** [comment] 2017-07-29 14:20
The regular unittests as well as the examples run fine for me with that DMD compiler on Windows 10. I used dub to run the tests. What did you use? Which Windows version are you on?

The example you posted above also runs fine for me, except that the assertion fails.

**Comment by mbierlee** [comment] 2017-07-29 14:22
The assertion fails because the `@Autowire` UDA must be written with a capital

**Comment by mbierlee** [comment] 2017-08-13 16:45
Unfortunately I am unable to reproduce this issue. I will close this for now. If you still encounter this issue, could you provide me with more information?

**Closed by mbierlee** 2017-08-13 16:45 UTC
